// Code generated by protoc-gen-go.
// source: xgsdk.proto
// DO NOT EDIT!

/*
Package xgsdk is a generated protocol buffer package.

It is generated from these files:
	xgsdk.proto

It has these top-level messages:
	RegisterReq
	VerifySessionReq
	VerifySessionData
	VerifySessionResp
	VerifyOrder
	VerifyOrderData
	VerifyOrderResp
	PayNtf
	PayRsp
*/
package xgsdk

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Command int32

const (
	Command_CMD_REGISTER_REQ      Command = 911
	Command_CMD_REGISTER_RSP      Command = 912
	Command_CMD_VERIFYSESSION_REQ Command = 913
	Command_CMD_VERIFYSESSION_RSP Command = 914
	Command_CMD_VERIFYORDER_REQ   Command = 915
	Command_CMD_VERIFYORDER_RSP   Command = 916
	Command_CMD_PAY_NTF           Command = 917
	Command_CMD_PAY_RSP           Command = 918
)

var Command_name = map[int32]string{
	911: "CMD_REGISTER_REQ",
	912: "CMD_REGISTER_RSP",
	913: "CMD_VERIFYSESSION_REQ",
	914: "CMD_VERIFYSESSION_RSP",
	915: "CMD_VERIFYORDER_REQ",
	916: "CMD_VERIFYORDER_RSP",
	917: "CMD_PAY_NTF",
	918: "CMD_PAY_RSP",
}
var Command_value = map[string]int32{
	"CMD_REGISTER_REQ":      911,
	"CMD_REGISTER_RSP":      912,
	"CMD_VERIFYSESSION_REQ": 913,
	"CMD_VERIFYSESSION_RSP": 914,
	"CMD_VERIFYORDER_REQ":   915,
	"CMD_VERIFYORDER_RSP":   916,
	"CMD_PAY_NTF":           917,
	"CMD_PAY_RSP":           918,
}

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}
func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (x *Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_value, data, "Command")
	if err != nil {
		return err
	}
	*x = Command(value)
	return nil
}

type RegisterReq struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}

func (m *RegisterReq) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type VerifySessionReq struct {
	AuthInfo         *string `protobuf:"bytes,1,req,name=authInfo" json:"authInfo,omitempty"`
	Version          *string `protobuf:"bytes,2,opt,name=version,def=" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifySessionReq) Reset()         { *m = VerifySessionReq{} }
func (m *VerifySessionReq) String() string { return proto.CompactTextString(m) }
func (*VerifySessionReq) ProtoMessage()    {}

func (m *VerifySessionReq) GetAuthInfo() string {
	if m != nil && m.AuthInfo != nil {
		return *m.AuthInfo
	}
	return ""
}

func (m *VerifySessionReq) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type VerifySessionData struct {
	SessionId        *string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
	UId              *string `protobuf:"bytes,2,opt,name=uId" json:"uId,omitempty"`
	UserName         *string `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	NickName         *string `protobuf:"bytes,4,opt,name=nickName" json:"nickName,omitempty"`
	State            *string `protobuf:"bytes,5,opt,name=state" json:"state,omitempty"`
	DeviceId         *string `protobuf:"bytes,6,opt,name=deviceId" json:"deviceId,omitempty"`
	Telephone        *string `protobuf:"bytes,7,opt,name=telephone" json:"telephone,omitempty"`
	Mail             *string `protobuf:"bytes,8,opt,name=mail" json:"mail,omitempty"`
	Sex              *string `protobuf:"bytes,9,opt,name=sex" json:"sex,omitempty"`
	Birthday         *string `protobuf:"bytes,10,opt,name=birthday" json:"birthday,omitempty"`
	SmallHeadIconUrl *string `protobuf:"bytes,11,opt,name=smallHeadIconUrl" json:"smallHeadIconUrl,omitempty"`
	BigHeadIconUrl   *string `protobuf:"bytes,12,opt,name=bigHeadIconUrl" json:"bigHeadIconUrl,omitempty"`
	Constellation    *string `protobuf:"bytes,13,opt,name=constellation" json:"constellation,omitempty"`
	Balance          *string `protobuf:"bytes,14,opt,name=balance" json:"balance,omitempty"`
	Level            *string `protobuf:"bytes,15,opt,name=level" json:"level,omitempty"`
	ChannelId        *string `protobuf:"bytes,16,opt,name=channelId" json:"channelId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifySessionData) Reset()         { *m = VerifySessionData{} }
func (m *VerifySessionData) String() string { return proto.CompactTextString(m) }
func (*VerifySessionData) ProtoMessage()    {}

func (m *VerifySessionData) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *VerifySessionData) GetUId() string {
	if m != nil && m.UId != nil {
		return *m.UId
	}
	return ""
}

func (m *VerifySessionData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *VerifySessionData) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *VerifySessionData) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *VerifySessionData) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *VerifySessionData) GetTelephone() string {
	if m != nil && m.Telephone != nil {
		return *m.Telephone
	}
	return ""
}

func (m *VerifySessionData) GetMail() string {
	if m != nil && m.Mail != nil {
		return *m.Mail
	}
	return ""
}

func (m *VerifySessionData) GetSex() string {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return ""
}

func (m *VerifySessionData) GetBirthday() string {
	if m != nil && m.Birthday != nil {
		return *m.Birthday
	}
	return ""
}

func (m *VerifySessionData) GetSmallHeadIconUrl() string {
	if m != nil && m.SmallHeadIconUrl != nil {
		return *m.SmallHeadIconUrl
	}
	return ""
}

func (m *VerifySessionData) GetBigHeadIconUrl() string {
	if m != nil && m.BigHeadIconUrl != nil {
		return *m.BigHeadIconUrl
	}
	return ""
}

func (m *VerifySessionData) GetConstellation() string {
	if m != nil && m.Constellation != nil {
		return *m.Constellation
	}
	return ""
}

func (m *VerifySessionData) GetBalance() string {
	if m != nil && m.Balance != nil {
		return *m.Balance
	}
	return ""
}

func (m *VerifySessionData) GetLevel() string {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return ""
}

func (m *VerifySessionData) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

type VerifySessionResp struct {
	Code             *int32             `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Msg              *string            `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	Data             *VerifySessionData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *VerifySessionResp) Reset()         { *m = VerifySessionResp{} }
func (m *VerifySessionResp) String() string { return proto.CompactTextString(m) }
func (*VerifySessionResp) ProtoMessage()    {}

func (m *VerifySessionResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *VerifySessionResp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *VerifySessionResp) GetData() *VerifySessionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifyOrder struct {
	OrderId          *string `protobuf:"bytes,1,req,name=orderId" json:"orderId,omitempty"`
	Sign             *string `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyOrder) Reset()         { *m = VerifyOrder{} }
func (m *VerifyOrder) String() string { return proto.CompactTextString(m) }
func (*VerifyOrder) ProtoMessage()    {}

func (m *VerifyOrder) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *VerifyOrder) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

type VerifyOrderData struct {
	AppId            *string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	SdkAppid         *string `protobuf:"bytes,2,opt,name=sdkAppid" json:"sdkAppid,omitempty"`
	ChannelId        *string `protobuf:"bytes,3,opt,name=channelId" json:"channelId,omitempty"`
	SdkUid           *string `protobuf:"bytes,4,opt,name=sdkUid" json:"sdkUid,omitempty"`
	OrderId          *string `protobuf:"bytes,5,opt,name=orderId" json:"orderId,omitempty"`
	AppGoodsId       *string `protobuf:"bytes,6,opt,name=appGoodsId" json:"appGoodsId,omitempty"`
	AppGoodsName     *string `protobuf:"bytes,7,opt,name=appGoodsName" json:"appGoodsName,omitempty"`
	AppGoodsDesc     *string `protobuf:"bytes,8,opt,name=appGoodsDesc" json:"appGoodsDesc,omitempty"`
	AppGoodsAmount   *string `protobuf:"bytes,9,opt,name=appGoodsAmount" json:"appGoodsAmount,omitempty"`
	TotalPrice       *string `protobuf:"bytes,10,opt,name=totalPrice" json:"totalPrice,omitempty"`
	OriginalPrice    *string `protobuf:"bytes,11,opt,name=originalPrice" json:"originalPrice,omitempty"`
	Custom           *string `protobuf:"bytes,12,opt,name=custom" json:"custom,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyOrderData) Reset()         { *m = VerifyOrderData{} }
func (m *VerifyOrderData) String() string { return proto.CompactTextString(m) }
func (*VerifyOrderData) ProtoMessage()    {}

func (m *VerifyOrderData) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *VerifyOrderData) GetSdkAppid() string {
	if m != nil && m.SdkAppid != nil {
		return *m.SdkAppid
	}
	return ""
}

func (m *VerifyOrderData) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *VerifyOrderData) GetSdkUid() string {
	if m != nil && m.SdkUid != nil {
		return *m.SdkUid
	}
	return ""
}

func (m *VerifyOrderData) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *VerifyOrderData) GetAppGoodsId() string {
	if m != nil && m.AppGoodsId != nil {
		return *m.AppGoodsId
	}
	return ""
}

func (m *VerifyOrderData) GetAppGoodsName() string {
	if m != nil && m.AppGoodsName != nil {
		return *m.AppGoodsName
	}
	return ""
}

func (m *VerifyOrderData) GetAppGoodsDesc() string {
	if m != nil && m.AppGoodsDesc != nil {
		return *m.AppGoodsDesc
	}
	return ""
}

func (m *VerifyOrderData) GetAppGoodsAmount() string {
	if m != nil && m.AppGoodsAmount != nil {
		return *m.AppGoodsAmount
	}
	return ""
}

func (m *VerifyOrderData) GetTotalPrice() string {
	if m != nil && m.TotalPrice != nil {
		return *m.TotalPrice
	}
	return ""
}

func (m *VerifyOrderData) GetOriginalPrice() string {
	if m != nil && m.OriginalPrice != nil {
		return *m.OriginalPrice
	}
	return ""
}

func (m *VerifyOrderData) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

type VerifyOrderResp struct {
	Code             *int32           `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Msg              *string          `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	Data             *VerifyOrderData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *VerifyOrderResp) Reset()         { *m = VerifyOrderResp{} }
func (m *VerifyOrderResp) String() string { return proto.CompactTextString(m) }
func (*VerifyOrderResp) ProtoMessage()    {}

func (m *VerifyOrderResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *VerifyOrderResp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *VerifyOrderResp) GetData() *VerifyOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PayNtf struct {
	OrderId          *string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	SdkUid           *string `protobuf:"bytes,2,opt,name=sdkUid" json:"sdkUid,omitempty"`
	PayStatus        *string `protobuf:"bytes,3,opt,name=payStatus" json:"payStatus,omitempty"`
	PayTime          *string `protobuf:"bytes,4,opt,name=payTime" json:"payTime,omitempty"`
	FailedDesc       *string `protobuf:"bytes,5,opt,name=failedDesc" json:"failedDesc,omitempty"`
	AppId            *string `protobuf:"bytes,6,opt,name=appId" json:"appId,omitempty"`
	ChannelId        *string `protobuf:"bytes,7,opt,name=channelId" json:"channelId,omitempty"`
	AppGoodsId       *string `protobuf:"bytes,8,opt,name=appGoodsId" json:"appGoodsId,omitempty"`
	AppGoodsName     *string `protobuf:"bytes,9,opt,name=appGoodsName" json:"appGoodsName,omitempty"`
	AppGoodsDesc     *string `protobuf:"bytes,10,opt,name=appGoodsDesc" json:"appGoodsDesc,omitempty"`
	AppGoodsAmount   *string `protobuf:"bytes,11,opt,name=appGoodsAmount" json:"appGoodsAmount,omitempty"`
	TotalPrice       *string `protobuf:"bytes,12,opt,name=totalPrice" json:"totalPrice,omitempty"`
	OriginalPrice    *string `protobuf:"bytes,13,opt,name=originalPrice" json:"originalPrice,omitempty"`
	ZoneId           *string `protobuf:"bytes,14,opt,name=zoneId" json:"zoneId,omitempty"`
	ServerId         *string `protobuf:"bytes,15,opt,name=serverId" json:"serverId,omitempty"`
	RoleId           *string `protobuf:"bytes,16,opt,name=roleId" json:"roleId,omitempty"`
	RoleName         *string `protobuf:"bytes,17,opt,name=roleName" json:"roleName,omitempty"`
	CurrencyName     *string `protobuf:"bytes,18,opt,name=currencyName" json:"currencyName,omitempty"`
	Custom           *string `protobuf:"bytes,19,opt,name=custom" json:"custom,omitempty"`
	Sign             *string `protobuf:"bytes,20,opt,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PayNtf) Reset()         { *m = PayNtf{} }
func (m *PayNtf) String() string { return proto.CompactTextString(m) }
func (*PayNtf) ProtoMessage()    {}

func (m *PayNtf) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func (m *PayNtf) GetSdkUid() string {
	if m != nil && m.SdkUid != nil {
		return *m.SdkUid
	}
	return ""
}

func (m *PayNtf) GetPayStatus() string {
	if m != nil && m.PayStatus != nil {
		return *m.PayStatus
	}
	return ""
}

func (m *PayNtf) GetPayTime() string {
	if m != nil && m.PayTime != nil {
		return *m.PayTime
	}
	return ""
}

func (m *PayNtf) GetFailedDesc() string {
	if m != nil && m.FailedDesc != nil {
		return *m.FailedDesc
	}
	return ""
}

func (m *PayNtf) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *PayNtf) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *PayNtf) GetAppGoodsId() string {
	if m != nil && m.AppGoodsId != nil {
		return *m.AppGoodsId
	}
	return ""
}

func (m *PayNtf) GetAppGoodsName() string {
	if m != nil && m.AppGoodsName != nil {
		return *m.AppGoodsName
	}
	return ""
}

func (m *PayNtf) GetAppGoodsDesc() string {
	if m != nil && m.AppGoodsDesc != nil {
		return *m.AppGoodsDesc
	}
	return ""
}

func (m *PayNtf) GetAppGoodsAmount() string {
	if m != nil && m.AppGoodsAmount != nil {
		return *m.AppGoodsAmount
	}
	return ""
}

func (m *PayNtf) GetTotalPrice() string {
	if m != nil && m.TotalPrice != nil {
		return *m.TotalPrice
	}
	return ""
}

func (m *PayNtf) GetOriginalPrice() string {
	if m != nil && m.OriginalPrice != nil {
		return *m.OriginalPrice
	}
	return ""
}

func (m *PayNtf) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *PayNtf) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *PayNtf) GetRoleId() string {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return ""
}

func (m *PayNtf) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *PayNtf) GetCurrencyName() string {
	if m != nil && m.CurrencyName != nil {
		return *m.CurrencyName
	}
	return ""
}

func (m *PayNtf) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

func (m *PayNtf) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

type PayRsp struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Msg              *string `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	OrderId          *string `protobuf:"bytes,3,opt,name=orderId" json:"orderId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PayRsp) Reset()         { *m = PayRsp{} }
func (m *PayRsp) String() string { return proto.CompactTextString(m) }
func (*PayRsp) ProtoMessage()    {}

func (m *PayRsp) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *PayRsp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *PayRsp) GetOrderId() string {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterEnum("xgsdk.Command", Command_name, Command_value)
}
