// Code generated by protoc-gen-go.
// source: immortaldb.proto
// DO NOT EDIT!

/*
Package immortaldb is a generated protocol buffer package.

It is generated from these files:
	immortaldb.proto

It has these top-level messages:
	Item
	ItemList
	Player
*/
package immortaldb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// discarding unused import google_protobuf "seasun.com/sirius/proto/google/protobuf/descriptor.pb"
// discarding unused import dbproto "seasun.com/sirius/proto/dbproxy.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Item struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func (m *Item) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ItemList struct {
	Items            []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemList) Reset()         { *m = ItemList{} }
func (m *ItemList) String() string { return proto.CompactTextString(m) }
func (*ItemList) ProtoMessage()    {}

func (m *ItemList) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// 用户角色对象示例
type Player struct {
	// 角色属性
	// 每一个属性对应mysql表中的一个字段
	// 字段名必须跟当前message的成员名一致
	// 类型也必须一致
	Account *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name    *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Level   *uint32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Exp     *uint32 `protobuf:"varint,4,req,name=exp" json:"exp,omitempty"`
	// bytes 对应mysql blob
	Extend []byte `protobuf:"bytes,5,opt,name=extend" json:"extend,omitempty"`
	// 自定义对象 对应mysql blob
	Itemlist         *ItemList `protobuf:"bytes,6,opt,name=itemlist" json:"itemlist,omitempty"`
	Roleid           *uint64   `protobuf:"varint,7,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}

func (m *Player) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Player) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Player) GetExp() uint32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Player) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

func (m *Player) GetItemlist() *ItemList {
	if m != nil {
		return m.Itemlist
	}
	return nil
}

func (m *Player) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

func init() {
}
