// Code generated by protoc-gen-go.
// source: online.proto
// DO NOT EDIT!

/*
Package onlineproto is a generated protocol buffer package.

It is generated from these files:
	online.proto

It has these top-level messages:
	CreateRoleReq
	CreateRoleRsp
	CreateAccountReq
	CreateAccountRsp
	SetOnlineReq
	SetOnlineRsp
	SetOfflineReq
	SetOfflineRsp
	AccountInfo
	GetAccountInfoReq
	GetAccountInfoRsp
	RenameReq
	RenameRsp
	LogoutReq
	LogoutRsp
	VerifyReq
	VerifyRsp
	RegisterGSReq
	RegisterGSRsp
*/
package onlineproto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import PbCommon "seasun.com/sirius/proto/common.pb"

// discarding unused import onlinedb "seasun.com/sirius/proto/onlinedb.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Command int32

const (
	// common.command.ONLINE_CMD_BEGIN = 801
	Command_CMD_SET_ONLINE_REQ     Command = 801
	Command_CMD_SET_ONLINE_RSP     Command = 802
	Command_CMD_SET_OFFLINE_REQ    Command = 803
	Command_CMD_SET_OFFLINE_RSP    Command = 804
	Command_CMD_HEARTBEAT_REQ      Command = 805
	Command_CMD_HEARTBEAT_RSP      Command = 806
	Command_CMD_LOGOUT_REQ         Command = 807
	Command_CMD_LOGOUT_RSP         Command = 808
	Command_CMD_VERIFY_REQ         Command = 809
	Command_CMD_VERIFY_RSP         Command = 810
	Command_CMD_REGISTERGS_REQ     Command = 811
	Command_CMD_REGISTERGS_RSP     Command = 812
	Command_CMD_GETACCOUNTINFO_REQ Command = 813
	Command_CMD_GETACCOUNTINFO_RSP Command = 814
	Command_CMD_CREATEROLE_REQ     Command = 815
	Command_CMD_CREATEROLE_RSP     Command = 816
	Command_CMD_RENAME_REQ         Command = 817
	Command_CMD_RENAME_RSP         Command = 818
)

var Command_name = map[int32]string{
	801: "CMD_SET_ONLINE_REQ",
	802: "CMD_SET_ONLINE_RSP",
	803: "CMD_SET_OFFLINE_REQ",
	804: "CMD_SET_OFFLINE_RSP",
	805: "CMD_HEARTBEAT_REQ",
	806: "CMD_HEARTBEAT_RSP",
	807: "CMD_LOGOUT_REQ",
	808: "CMD_LOGOUT_RSP",
	809: "CMD_VERIFY_REQ",
	810: "CMD_VERIFY_RSP",
	811: "CMD_REGISTERGS_REQ",
	812: "CMD_REGISTERGS_RSP",
	813: "CMD_GETACCOUNTINFO_REQ",
	814: "CMD_GETACCOUNTINFO_RSP",
	815: "CMD_CREATEROLE_REQ",
	816: "CMD_CREATEROLE_RSP",
	817: "CMD_RENAME_REQ",
	818: "CMD_RENAME_RSP",
}
var Command_value = map[string]int32{
	"CMD_SET_ONLINE_REQ":     801,
	"CMD_SET_ONLINE_RSP":     802,
	"CMD_SET_OFFLINE_REQ":    803,
	"CMD_SET_OFFLINE_RSP":    804,
	"CMD_HEARTBEAT_REQ":      805,
	"CMD_HEARTBEAT_RSP":      806,
	"CMD_LOGOUT_REQ":         807,
	"CMD_LOGOUT_RSP":         808,
	"CMD_VERIFY_REQ":         809,
	"CMD_VERIFY_RSP":         810,
	"CMD_REGISTERGS_REQ":     811,
	"CMD_REGISTERGS_RSP":     812,
	"CMD_GETACCOUNTINFO_REQ": 813,
	"CMD_GETACCOUNTINFO_RSP": 814,
	"CMD_CREATEROLE_REQ":     815,
	"CMD_CREATEROLE_RSP":     816,
	"CMD_RENAME_REQ":         817,
	"CMD_RENAME_RSP":         818,
}

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}
func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (x *Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_value, data, "Command")
	if err != nil {
		return err
	}
	*x = Command(value)
	return nil
}

type Errcode int32

const (
	Errcode_ERR_RWCACHE         Errcode = 10801
	Errcode_ERR_RWDB            Errcode = 10802
	Errcode_ERR_UNPACK          Errcode = 10803
	Errcode_ERR_SAMEACCOUNT     Errcode = 10804
	Errcode_ERR_CORRUPTION      Errcode = 10805
	Errcode_ERR_NODATA          Errcode = 10806
	Errcode_ERR_GSERR           Errcode = 10807
	Errcode_ERR_TIMEOUT         Errcode = 10808
	Errcode_ERR_DICONNECT       Errcode = 10809
	Errcode_ERR_NOTEXIST        Errcode = 10810
	Errcode_ERR_INVALIDTOKEN    Errcode = 10811
	Errcode_ERR_NAMENOTMATCH    Errcode = 10812
	Errcode_ERR_ALREADYREGISTER Errcode = 10813
	Errcode_ERR_NETSEND         Errcode = 10814
	Errcode_ERR_PACK            Errcode = 10815
	Errcode_ERR_SERVERDISCONN   Errcode = 10816
	Errcode_ERR_GSNOTEXIST      Errcode = 10817
	Errcode_ERR_MAXROLE         Errcode = 10818
)

var Errcode_name = map[int32]string{
	10801: "ERR_RWCACHE",
	10802: "ERR_RWDB",
	10803: "ERR_UNPACK",
	10804: "ERR_SAMEACCOUNT",
	10805: "ERR_CORRUPTION",
	10806: "ERR_NODATA",
	10807: "ERR_GSERR",
	10808: "ERR_TIMEOUT",
	10809: "ERR_DICONNECT",
	10810: "ERR_NOTEXIST",
	10811: "ERR_INVALIDTOKEN",
	10812: "ERR_NAMENOTMATCH",
	10813: "ERR_ALREADYREGISTER",
	10814: "ERR_NETSEND",
	10815: "ERR_PACK",
	10816: "ERR_SERVERDISCONN",
	10817: "ERR_GSNOTEXIST",
	10818: "ERR_MAXROLE",
}
var Errcode_value = map[string]int32{
	"ERR_RWCACHE":         10801,
	"ERR_RWDB":            10802,
	"ERR_UNPACK":          10803,
	"ERR_SAMEACCOUNT":     10804,
	"ERR_CORRUPTION":      10805,
	"ERR_NODATA":          10806,
	"ERR_GSERR":           10807,
	"ERR_TIMEOUT":         10808,
	"ERR_DICONNECT":       10809,
	"ERR_NOTEXIST":        10810,
	"ERR_INVALIDTOKEN":    10811,
	"ERR_NAMENOTMATCH":    10812,
	"ERR_ALREADYREGISTER": 10813,
	"ERR_NETSEND":         10814,
	"ERR_PACK":            10815,
	"ERR_SERVERDISCONN":   10816,
	"ERR_GSNOTEXIST":      10817,
	"ERR_MAXROLE":         10818,
}

func (x Errcode) Enum() *Errcode {
	p := new(Errcode)
	*p = x
	return p
}
func (x Errcode) String() string {
	return proto.EnumName(Errcode_name, int32(x))
}
func (x *Errcode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Errcode_value, data, "Errcode")
	if err != nil {
		return err
	}
	*x = Errcode(value)
	return nil
}

type CreateRoleReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Aid              *uint32 `protobuf:"varint,3,req,name=aid" json:"aid,omitempty"`
	Sid              *uint32 `protobuf:"varint,4,req,name=sid" json:"sid,omitempty"`
	Extend           []byte  `protobuf:"bytes,5,opt,name=extend" json:"extend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoleReq) Reset()         { *m = CreateRoleReq{} }
func (m *CreateRoleReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoleReq) ProtoMessage()    {}

func (m *CreateRoleReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CreateRoleReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateRoleReq) GetAid() uint32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *CreateRoleReq) GetSid() uint32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *CreateRoleReq) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type CreateRoleRsp struct {
	Roleid           *uint64 `protobuf:"varint,1,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoleRsp) Reset()         { *m = CreateRoleRsp{} }
func (m *CreateRoleRsp) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRsp) ProtoMessage()    {}

func (m *CreateRoleRsp) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type CreateAccountReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}

func (m *CreateAccountReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type CreateAccountRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateAccountRsp) Reset()         { *m = CreateAccountRsp{} }
func (m *CreateAccountRsp) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRsp) ProtoMessage()    {}

type SetOnlineReq struct {
	Account *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	// name 已经不需要, 使用roleid来唯一确定一个角色
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Gid              *int64  `protobuf:"zigzag64,3,req,name=gid" json:"gid,omitempty"`
	Token            []byte  `protobuf:"bytes,4,req,name=token" json:"token,omitempty"`
	Roleid           *uint64 `protobuf:"varint,5,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetOnlineReq) Reset()         { *m = SetOnlineReq{} }
func (m *SetOnlineReq) String() string { return proto.CompactTextString(m) }
func (*SetOnlineReq) ProtoMessage()    {}

func (m *SetOnlineReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *SetOnlineReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SetOnlineReq) GetGid() int64 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *SetOnlineReq) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SetOnlineReq) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type SetOnlineRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetOnlineRsp) Reset()         { *m = SetOnlineRsp{} }
func (m *SetOnlineRsp) String() string { return proto.CompactTextString(m) }
func (*SetOnlineRsp) ProtoMessage()    {}

type SetOfflineReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Roleid           *uint64 `protobuf:"varint,3,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetOfflineReq) Reset()         { *m = SetOfflineReq{} }
func (m *SetOfflineReq) String() string { return proto.CompactTextString(m) }
func (*SetOfflineReq) ProtoMessage()    {}

func (m *SetOfflineReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *SetOfflineReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SetOfflineReq) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type SetOfflineRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetOfflineRsp) Reset()         { *m = SetOfflineRsp{} }
func (m *SetOfflineRsp) String() string { return proto.CompactTextString(m) }
func (*SetOfflineRsp) ProtoMessage()    {}

type AccountInfo struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Regtime          *uint64 `protobuf:"varint,3,req,name=regtime" json:"regtime,omitempty"`
	Aid              *uint32 `protobuf:"varint,4,req,name=aid" json:"aid,omitempty"`
	Sid              *uint32 `protobuf:"varint,5,req,name=sid" json:"sid,omitempty"`
	Extend           []byte  `protobuf:"bytes,6,opt,name=extend" json:"extend,omitempty"`
	Roleid           *uint64 `protobuf:"varint,7,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}

func (m *AccountInfo) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AccountInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AccountInfo) GetRegtime() uint64 {
	if m != nil && m.Regtime != nil {
		return *m.Regtime
	}
	return 0
}

func (m *AccountInfo) GetAid() uint32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *AccountInfo) GetSid() uint32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *AccountInfo) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

func (m *AccountInfo) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type GetAccountInfoReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAccountInfoReq) Reset()         { *m = GetAccountInfoReq{} }
func (m *GetAccountInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoReq) ProtoMessage()    {}

func (m *GetAccountInfoReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type GetAccountInfoRsp struct {
	Accounts         []*AccountInfo `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetAccountInfoRsp) Reset()         { *m = GetAccountInfoRsp{} }
func (m *GetAccountInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccountInfoRsp) ProtoMessage()    {}

func (m *GetAccountInfoRsp) GetAccounts() []*AccountInfo {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type RenameReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Roleid           *uint64 `protobuf:"varint,2,req,name=roleid" json:"roleid,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RenameReq) Reset()         { *m = RenameReq{} }
func (m *RenameReq) String() string { return proto.CompactTextString(m) }
func (*RenameReq) ProtoMessage()    {}

func (m *RenameReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RenameReq) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

func (m *RenameReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type RenameRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RenameRsp) Reset()         { *m = RenameRsp{} }
func (m *RenameRsp) String() string { return proto.CompactTextString(m) }
func (*RenameRsp) ProtoMessage()    {}

type LogoutReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}

func (m *LogoutReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type LogoutRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LogoutRsp) Reset()         { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()    {}

type VerifyReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Token            []byte  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	Roleid           *uint64 `protobuf:"varint,4,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}

func (m *VerifyReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *VerifyReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *VerifyReq) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *VerifyReq) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type VerifyRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *VerifyRsp) Reset()         { *m = VerifyRsp{} }
func (m *VerifyRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyRsp) ProtoMessage()    {}

// CMD_REGISTERGS_REG
type RegisterGSReq struct {
	Addr             *PbCommon.Addr `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RegisterGSReq) Reset()         { *m = RegisterGSReq{} }
func (m *RegisterGSReq) String() string { return proto.CompactTextString(m) }
func (*RegisterGSReq) ProtoMessage()    {}

func (m *RegisterGSReq) GetAddr() *PbCommon.Addr {
	if m != nil {
		return m.Addr
	}
	return nil
}

// CMD_REGISTERGS_RSP
type RegisterGSRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegisterGSRsp) Reset()         { *m = RegisterGSRsp{} }
func (m *RegisterGSRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterGSRsp) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("onlineproto.Command", Command_name, Command_value)
	proto.RegisterEnum("onlineproto.Errcode", Errcode_name, Errcode_value)
}
