// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package PbLogin is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	VerifyReq
	VerifyRsp
	LogonReq
	LogonRsp
	CreateReq
	CreateRsp
	GetAllAreaReq
	GetAllAreaRsp
*/
package PbLogin

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import PbCommon "seasun.com/sirius/proto/common.pb"
import onlineproto "seasun.com/sirius/proto/online.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Command int32

const (
	// common.command.LOGIN_CMD_BEGIN = 401
	Command_CMD_VERIFY_REQ       Command = 401
	Command_CMD_VERIFY_RSP       Command = 402
	Command_CMD_GET_ALL_AREA_REQ Command = 403
	Command_CMD_GET_ALL_AREA_RSP Command = 404
	Command_CMD_LOGON_REQ        Command = 405
	Command_CMD_LOGON_RSP        Command = 406
	Command_CMD_CREATE_REQ       Command = 407
	Command_CMD_CREATE_RSP       Command = 408
)

var Command_name = map[int32]string{
	401: "CMD_VERIFY_REQ",
	402: "CMD_VERIFY_RSP",
	403: "CMD_GET_ALL_AREA_REQ",
	404: "CMD_GET_ALL_AREA_RSP",
	405: "CMD_LOGON_REQ",
	406: "CMD_LOGON_RSP",
	407: "CMD_CREATE_REQ",
	408: "CMD_CREATE_RSP",
}
var Command_value = map[string]int32{
	"CMD_VERIFY_REQ":       401,
	"CMD_VERIFY_RSP":       402,
	"CMD_GET_ALL_AREA_REQ": 403,
	"CMD_GET_ALL_AREA_RSP": 404,
	"CMD_LOGON_REQ":        405,
	"CMD_LOGON_RSP":        406,
	"CMD_CREATE_REQ":       407,
	"CMD_CREATE_RSP":       408,
}

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}
func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (x *Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_value, data, "Command")
	if err != nil {
		return err
	}
	*x = Command(value)
	return nil
}

type Errcode int32

const (
	Errcode_ERR_INTER           Errcode = 10401
	Errcode_ERR_VERIFY_ERR      Errcode = 10402
	Errcode_ERR_INVALID_PARAM   Errcode = 10403
	Errcode_ERR_TIMEOUT         Errcode = 10404
	Errcode_ERR_HANDLE_LAST_REQ Errcode = 10405
)

var Errcode_name = map[int32]string{
	10401: "ERR_INTER",
	10402: "ERR_VERIFY_ERR",
	10403: "ERR_INVALID_PARAM",
	10404: "ERR_TIMEOUT",
	10405: "ERR_HANDLE_LAST_REQ",
}
var Errcode_value = map[string]int32{
	"ERR_INTER":           10401,
	"ERR_VERIFY_ERR":      10402,
	"ERR_INVALID_PARAM":   10403,
	"ERR_TIMEOUT":         10404,
	"ERR_HANDLE_LAST_REQ": 10405,
}

func (x Errcode) Enum() *Errcode {
	p := new(Errcode)
	*p = x
	return p
}
func (x Errcode) String() string {
	return proto.EnumName(Errcode_name, int32(x))
}
func (x *Errcode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Errcode_value, data, "Errcode")
	if err != nil {
		return err
	}
	*x = Errcode(value)
	return nil
}

type VerifyReq struct {
	Platform         *string `protobuf:"bytes,1,req,name=platform" json:"platform,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	ThirdKey         *string `protobuf:"bytes,3,req,name=third_key" json:"third_key,omitempty"`
	Resv             *int32  `protobuf:"zigzag32,4,opt,name=resv" json:"resv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}

func (m *VerifyReq) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *VerifyReq) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *VerifyReq) GetThirdKey() string {
	if m != nil && m.ThirdKey != nil {
		return *m.ThirdKey
	}
	return ""
}

func (m *VerifyReq) GetResv() int32 {
	if m != nil && m.Resv != nil {
		return *m.Resv
	}
	return 0
}

type VerifyRsp struct {
	Roles            []*onlineproto.AccountInfo `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	AllAddrs         []*PbCommon.AreaSrvInfo    `protobuf:"bytes,2,rep,name=all_addrs" json:"all_addrs,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *VerifyRsp) Reset()         { *m = VerifyRsp{} }
func (m *VerifyRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyRsp) ProtoMessage()    {}

func (m *VerifyRsp) GetRoles() []*onlineproto.AccountInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *VerifyRsp) GetAllAddrs() []*PbCommon.AreaSrvInfo {
	if m != nil {
		return m.AllAddrs
	}
	return nil
}

type LogonReq struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Aid              *int32  `protobuf:"zigzag32,2,req,name=aid" json:"aid,omitempty"`
	Sid              *int32  `protobuf:"zigzag32,3,req,name=sid" json:"sid,omitempty"`
	Role             *string `protobuf:"bytes,4,req,name=role" json:"role,omitempty"`
	Roleid           *uint64 `protobuf:"varint,5,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogonReq) Reset()         { *m = LogonReq{} }
func (m *LogonReq) String() string { return proto.CompactTextString(m) }
func (*LogonReq) ProtoMessage()    {}

func (m *LogonReq) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LogonReq) GetAid() int32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *LogonReq) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *LogonReq) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *LogonReq) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type LogonRsp struct {
	GsIp             *string `protobuf:"bytes,1,req,name=gs_ip" json:"gs_ip,omitempty"`
	GsPort           *int32  `protobuf:"zigzag32,2,req,name=gs_port" json:"gs_port,omitempty"`
	GsId             *int64  `protobuf:"zigzag64,3,req,name=gs_id" json:"gs_id,omitempty"`
	Key              []byte  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Resv             *int32  `protobuf:"zigzag32,5,opt,name=resv" json:"resv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogonRsp) Reset()         { *m = LogonRsp{} }
func (m *LogonRsp) String() string { return proto.CompactTextString(m) }
func (*LogonRsp) ProtoMessage()    {}

func (m *LogonRsp) GetGsIp() string {
	if m != nil && m.GsIp != nil {
		return *m.GsIp
	}
	return ""
}

func (m *LogonRsp) GetGsPort() int32 {
	if m != nil && m.GsPort != nil {
		return *m.GsPort
	}
	return 0
}

func (m *LogonRsp) GetGsId() int64 {
	if m != nil && m.GsId != nil {
		return *m.GsId
	}
	return 0
}

func (m *LogonRsp) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *LogonRsp) GetResv() int32 {
	if m != nil && m.Resv != nil {
		return *m.Resv
	}
	return 0
}

type CreateReq struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Aid              *int32  `protobuf:"zigzag32,2,req,name=aid" json:"aid,omitempty"`
	Sid              *int32  `protobuf:"zigzag32,3,req,name=sid" json:"sid,omitempty"`
	Role             *string `protobuf:"bytes,4,req,name=role" json:"role,omitempty"`
	Extend           []byte  `protobuf:"bytes,5,req,name=extend" json:"extend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}

func (m *CreateReq) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *CreateReq) GetAid() int32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *CreateReq) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *CreateReq) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *CreateReq) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type CreateRsp struct {
	Roleid           *uint64 `protobuf:"varint,1,req,name=roleid" json:"roleid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRsp) Reset()         { *m = CreateRsp{} }
func (m *CreateRsp) String() string { return proto.CompactTextString(m) }
func (*CreateRsp) ProtoMessage()    {}

func (m *CreateRsp) GetRoleid() uint64 {
	if m != nil && m.Roleid != nil {
		return *m.Roleid
	}
	return 0
}

type GetAllAreaReq struct {
	Resv             *int32 `protobuf:"zigzag32,1,opt,name=resv" json:"resv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllAreaReq) Reset()         { *m = GetAllAreaReq{} }
func (m *GetAllAreaReq) String() string { return proto.CompactTextString(m) }
func (*GetAllAreaReq) ProtoMessage()    {}

func (m *GetAllAreaReq) GetResv() int32 {
	if m != nil && m.Resv != nil {
		return *m.Resv
	}
	return 0
}

type GetAllAreaRsp struct {
	Infos            []*PbCommon.AreaSrvInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetAllAreaRsp) Reset()         { *m = GetAllAreaRsp{} }
func (m *GetAllAreaRsp) String() string { return proto.CompactTextString(m) }
func (*GetAllAreaRsp) ProtoMessage()    {}

func (m *GetAllAreaRsp) GetInfos() []*PbCommon.AreaSrvInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterEnum("PbLogin.Command", Command_name, Command_value)
	proto.RegisterEnum("PbLogin.Errcode", Errcode_name, Errcode_value)
}
